Repository hwsc-org/hwsc-api-blocks, pull requests merged in 2019-02, with the labels that each got.

#108 Add Token in services for authorization
  generate_int_proto.sh
  int/hwsc-app-gateway-svc/proto/document.pb.go
  int/hwsc-app-gateway-svc/proto/hwsc-app-gateway-svc.pb.go
  int/hwsc-app-gateway-svc/proto/hwsc-app-gateway-svc.proto
  int/hwsc-app-gateway-svc/proto/hwsc-app-gateway-svc_pb.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-app-gateway-svc_pb.js
  int/hwsc-app-gateway-svc/proto/hwsc-app-gateway-svc_pb_service.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-app-gateway-svc_pb_service.js
  int/hwsc-app-gateway-svc/proto/hwsc-document-svc.pb.go
  int/hwsc-app-gateway-svc/proto/hwsc-document-svc_pb.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-document-svc_pb.js
  int/hwsc-app-gateway-svc/proto/hwsc-file-transaction-svc.pb.go
  int/hwsc-app-gateway-svc/proto/hwsc-file-transaction-svc_pb.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-file-transaction-svc_pb.js
  int/hwsc-app-gateway-svc/proto/hwsc-user-svc.pb.go
  int/hwsc-app-gateway-svc/proto/hwsc-user-svc_pb.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-user-svc_pb.js
  int/hwsc-app-gateway-svc/proto/hwsc-user-svc_pb_service.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-user-svc_pb_service.js
  int/hwsc-app-gateway-svc/proto/token.pb.go
  int/hwsc-app-gateway-svc/proto/token_pb.d.ts
  int/hwsc-app-gateway-svc/proto/token_pb.js
  int/hwsc-app-gateway-svc/proto/token_pb_service.d.ts
  int/hwsc-app-gateway-svc/proto/token_pb_service.js
  int/hwsc-app-gateway-svc/proto/user.pb.go
  int/hwsc-document-svc/proto/document.pb.go
  int/hwsc-document-svc/proto/hwsc-document-svc.pb.go
  int/hwsc-document-svc/proto/hwsc-document-svc.proto
  int/hwsc-document-svc/proto/token.pb.go
  int/hwsc-file-transaction-svc/proto/hwsc-file-transaction-svc.proto
  int/hwsc-file-transaction-svc/proto/hwsc_file_transaction_svc_pb2.py
  int/hwsc-file-transaction-svc/proto/token_pb2.py
  int/hwsc-file-transaction-svc/proto/token_pb2_grpc.py
  int/hwsc-grpc-sample-svc/proto/hwsc-grpc-sample-svc.pb.go
  int/hwsc-user-svc/proto/hwsc-user-svc.pb.go
  int/hwsc-user-svc/proto/hwsc-user-svc.proto
  int/hwsc-user-svc/proto/token.pb.go
  int/hwsc-user-svc/proto/user.pb.go
  lib/token.proto
Labels: enhancement

#109 Add Secret
  generate_int_proto.sh
  int/hwsc-app-gateway-svc/proto/hwsc-app-gateway-svc.proto
  int/hwsc-app-gateway-svc/proto/hwsc-document-svc.pb.go
  int/hwsc-app-gateway-svc/proto/hwsc-document-svc_pb.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-document-svc_pb.js
  int/hwsc-app-gateway-svc/proto/hwsc-file-transaction-svc.pb.go
  int/hwsc-app-gateway-svc/proto/hwsc-file-transaction-svc_pb.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-file-transaction-svc_pb.js
  int/hwsc-app-gateway-svc/proto/hwsc-user-svc.pb.go
  int/hwsc-app-gateway-svc/proto/hwsc-user-svc_pb.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-user-svc_pb.js
  int/hwsc-app-gateway-svc/proto/secret.pb.go
  int/hwsc-app-gateway-svc/proto/secret_pb.d.ts
  int/hwsc-app-gateway-svc/proto/secret_pb.js
  int/hwsc-app-gateway-svc/proto/secret_pb_service.d.ts
  int/hwsc-app-gateway-svc/proto/secret_pb_service.js
  int/hwsc-document-svc/proto/hwsc-document-svc.pb.go
  int/hwsc-document-svc/proto/hwsc-document-svc.proto
  int/hwsc-document-svc/proto/secret.pb.go
  int/hwsc-file-transaction-svc/proto/hwsc-file-transaction-svc.proto
  int/hwsc-file-transaction-svc/proto/hwsc_file_transaction_svc_pb2.py
  int/hwsc-file-transaction-svc/proto/secret_pb2.py
  int/hwsc-file-transaction-svc/proto/secret_pb2_grpc.py
  int/hwsc-user-svc/proto/hwsc-user-svc.pb.go
  int/hwsc-user-svc/proto/hwsc-user-svc.proto
  int/hwsc-user-svc/proto/secret.pb.go
  lib/secret.proto
  lib/user.proto
Labels: enhancement

#110 Implement web token with header, payload, signature
  int/hwsc-app-gateway-svc/proto/token.pb.go
  int/hwsc-app-gateway-svc/proto/token_pb.d.ts
  int/hwsc-app-gateway-svc/proto/token_pb.js
  int/hwsc-document-svc/proto/token.pb.go
  int/hwsc-file-transaction-svc/proto/token_pb2.py
  int/hwsc-user-svc/proto/token.pb.go
  lib/token.proto
Labels: enhancement

#111 Integrate and test authenticateUser service
  int/hwsc-user-svc/hwsc-user-svc.js
  integration_tests/test_user_svc_client.js
Labels: enhancement

#112 Implement Authority and token string
  generate_int_proto.sh
  int/hwsc-app-gateway-svc/proto/authority.pb.go
  int/hwsc-app-gateway-svc/proto/authority_pb.d.ts
  int/hwsc-app-gateway-svc/proto/authority_pb.js
  int/hwsc-app-gateway-svc/proto/authority_pb_service.d.ts
  int/hwsc-app-gateway-svc/proto/authority_pb_service.js
  int/hwsc-app-gateway-svc/proto/hwsc-app-gateway-svc.pb.go
  int/hwsc-app-gateway-svc/proto/hwsc-app-gateway-svc.proto
  int/hwsc-app-gateway-svc/proto/hwsc-app-gateway-svc_pb.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-app-gateway-svc_pb.js
  int/hwsc-app-gateway-svc/proto/hwsc-document-svc.pb.go
  int/hwsc-app-gateway-svc/proto/hwsc-document-svc_pb.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-document-svc_pb.js
  int/hwsc-app-gateway-svc/proto/hwsc-file-transaction-svc.pb.go
  int/hwsc-app-gateway-svc/proto/hwsc-file-transaction-svc_pb.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-file-transaction-svc_pb.js
  int/hwsc-app-gateway-svc/proto/hwsc-user-svc.pb.go
  int/hwsc-app-gateway-svc/proto/hwsc-user-svc_pb.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-user-svc_pb.js
  int/hwsc-app-gateway-svc/proto/secret.pb.go
  int/hwsc-app-gateway-svc/proto/secret_pb.d.ts
  int/hwsc-app-gateway-svc/proto/secret_pb.js
  int/hwsc-app-gateway-svc/proto/secret_pb_service.d.ts
  int/hwsc-app-gateway-svc/proto/secret_pb_service.js
  int/hwsc-app-gateway-svc/proto/token.pb.go
  int/hwsc-app-gateway-svc/proto/token_pb.d.ts
  int/hwsc-app-gateway-svc/proto/token_pb.js
  int/hwsc-app-gateway-svc/proto/token_pb_service.d.ts
  int/hwsc-app-gateway-svc/proto/token_pb_service.js
  int/hwsc-document-svc/proto/authority.pb.go
  int/hwsc-document-svc/proto/hwsc-document-svc.pb.go
  int/hwsc-document-svc/proto/hwsc-document-svc.proto
  int/hwsc-document-svc/proto/secret.pb.go
  int/hwsc-document-svc/proto/token.pb.go
  int/hwsc-file-transaction-svc/proto/authority_pb2.py
  int/hwsc-file-transaction-svc/proto/authority_pb2_grpc.py
  int/hwsc-file-transaction-svc/proto/hwsc-file-transaction-svc.proto
  int/hwsc-file-transaction-svc/proto/hwsc_file_transaction_svc_pb2.py
  int/hwsc-file-transaction-svc/proto/token_pb2.py
  int/hwsc-file-transaction-svc/proto/token_pb2_grpc.py
  int/hwsc-user-svc/proto/authority.pb.go
  int/hwsc-user-svc/proto/hwsc-user-svc.pb.go
  int/hwsc-user-svc/proto/hwsc-user-svc.proto
  int/hwsc-user-svc/proto/secret.pb.go
  int/hwsc-user-svc/proto/token.pb.go
  lib/authority.proto
  lib/token.proto
Labels: enhancement

#116 Ashley/update env v.1
  int/hwsc-file-transaction-svc/hwsc-file-transaction-svc.js
Labels: enhancement

#115 Clean up hard code
  integration_tests/test_user_svc_client.js
Labels: enhancement

#117 Fix imports and redundant protocol buffers
  generate_int_proto.sh
  int/hwsc-app-gateway-svc/app/hwsc-app-gateway-svc.pb.go
  int/hwsc-app-gateway-svc/app/hwsc-app-gateway-svc.proto
  int/hwsc-app-gateway-svc/hwsc-app-gateway-svc.js
  int/hwsc-app-gateway-svc/proto/authority.pb.go
  int/hwsc-app-gateway-svc/proto/authority_pb.d.ts
  int/hwsc-app-gateway-svc/proto/authority_pb.js
  int/hwsc-app-gateway-svc/proto/authority_pb_service.d.ts
  int/hwsc-app-gateway-svc/proto/authority_pb_service.js
  int/hwsc-app-gateway-svc/proto/document.pb.go
  int/hwsc-app-gateway-svc/proto/document_pb.d.ts
  int/hwsc-app-gateway-svc/proto/document_pb.js
  int/hwsc-app-gateway-svc/proto/document_pb_service.d.ts
  int/hwsc-app-gateway-svc/proto/document_pb_service.js
  int/hwsc-app-gateway-svc/proto/hwsc-app-gateway-svc_pb.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-app-gateway-svc_pb.js
  int/hwsc-app-gateway-svc/proto/hwsc-app-gateway-svc_pb_service.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-app-gateway-svc_pb_service.js
  int/hwsc-app-gateway-svc/proto/hwsc-document-svc.pb.go
  int/hwsc-app-gateway-svc/proto/hwsc-document-svc_pb.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-document-svc_pb.js
  int/hwsc-app-gateway-svc/proto/hwsc-document-svc_pb_service.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-document-svc_pb_service.js
  int/hwsc-app-gateway-svc/proto/hwsc-file-transaction-svc_pb.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-file-transaction-svc_pb.js
  int/hwsc-app-gateway-svc/proto/hwsc-file-transaction-svc_pb_service.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-file-transaction-svc_pb_service.js
  int/hwsc-app-gateway-svc/proto/hwsc-user-svc_pb.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-user-svc_pb.js
  int/hwsc-app-gateway-svc/proto/hwsc-user-svc_pb_service.d.ts
  int/hwsc-app-gateway-svc/proto/hwsc-user-svc_pb_service.js
  int/hwsc-app-gateway-svc/proto/user.pb.go
  int/hwsc-app-gateway-svc/proto/user_pb.d.ts
  int/hwsc-app-gateway-svc/proto/user_pb.js
  int/hwsc-app-gateway-svc/proto/user_pb_service.d.ts
  int/hwsc-app-gateway-svc/proto/user_pb_service.js
  int/hwsc-document-svc/document/hwsc-document-svc.pb.go
  int/hwsc-document-svc/document/hwsc-document-svc.proto
  int/hwsc-document-svc/hwsc-document-svc.js
  int/hwsc-file-transaction-svc/file/hwsc-file-transaction-svc.pb.go
  int/hwsc-file-transaction-svc/file/hwsc-file-transaction-svc.proto
  int/hwsc-file-transaction-svc/file/hwsc_file_transaction_svc_pb2.py
  int/hwsc-file-transaction-svc/file/hwsc_file_transaction_svc_pb2_grpc.py
  int/hwsc-file-transaction-svc/file/lib/authority_pb2.py
  int/hwsc-file-transaction-svc/file/lib/authority_pb2_grpc.py
  int/hwsc-file-transaction-svc/hwsc-file-transaction-svc.js
  int/hwsc-user-svc/hwsc-user-svc.js
  int/hwsc-user-svc/proto/authority.pb.go
  int/hwsc-user-svc/proto/hwsc-user-svc.pb.go
  int/hwsc-user-svc/user/hwsc-user-svc.pb.go
  int/hwsc-user-svc/user/hwsc-user-svc.proto
  lib/authority.pb.go
  lib/authority.proto
  lib/document.pb.go
  lib/document.proto
  lib/user.pb.go
  lib/user.proto
Labels: bug

#118 Fix/filetrans
  generate_int_proto.sh
  int/hwsc-app-gateway-svc/app/hwsc-app-gateway-svc_pb.d.ts
  int/hwsc-app-gateway-svc/app/hwsc-app-gateway-svc_pb.js
  int/hwsc-app-gateway-svc/app/hwsc-app-gateway-svc_pb_service.d.ts
  int/hwsc-app-gateway-svc/app/hwsc-app-gateway-svc_pb_service.js
  int/hwsc-file-transaction-svc/file/lib/authority.proto
Labels: bug

#119 Add fields for in authority.proto and user.proto to support user-svc
  int/hwsc-file-transaction-svc/file/lib/authority.proto
  int/hwsc-file-transaction-svc/file/lib/authority_pb2.py
  lib/authority.pb.go
  lib/authority.proto
  lib/user.pb.go
  lib/user.proto
Labels: enhancement

#120 Fix protocol buffers and tests
  .eslintrc.json
  index.js
  int/hwsc-app-gateway-svc/hwsc-app-gateway-svc.js
  int/hwsc-document-svc/hwsc-document-svc.js
  int/hwsc-file-transaction-svc/hwsc-file-transaction-svc.js
  int/hwsc-user-svc/hwsc-user-svc.js
  integration_tests/test_document_svc_client.js
  integration_tests/test_file_transaction_svc_client.js
  package-lock.json
  package.json
Labels: bug, enhancement

#121 Integrate NewSecret
  int/hwsc-user-svc/hwsc-user-svc.js
  integration_tests/test_user_svc_client.js
Labels: enhancement

#122 Integrate Get Secret
  int/hwsc-user-svc/hwsc-user-svc.js
  integration_tests/test_user_svc_client.js
Labels: enhancement

#123 Integrate GetToken
  int/hwsc-user-svc/hwsc-user-svc.js
  integration_tests/test_user_svc_client.js
Labels: enhancement

#124 Integrate VerifyToken
  int/hwsc-user-svc/hwsc-user-svc.js
  integration_tests/test_user_svc_client.js
Labels: enhancement

#125 Remove outdated comments and rename services
  int/hwsc-user-svc/user/hwsc-user-svc.pb.go
  int/hwsc-user-svc/user/hwsc-user-svc.proto
Labels: enhancement

#126 Update user service names in js files
  int/hwsc-user-svc/hwsc-user-svc.js
  integration_tests/test_user_svc_client.js
Labels: enhancement
